server:
  port: 9000

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/settlement?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
